
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function Privacy() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-grow py-16">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <h1 className="text-3xl font-bold mb-8">Privacy Policy</h1>
            
            <div className="prose max-w-none">
              <p className="mb-4">Last Updated: April 4, 2025</p>
              
              <h2 className="text-2xl font-semibold mt-8 mb-4">1. Introduction</h2>
              <p className="mb-4">
                StartupFundr ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by StartupFundr.
              </p>
              <p className="mb-4">
                This Privacy Policy applies to our website, and its associated subdomains (collectively, our "Service") alongside our application, StartupFundr. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
              </p>
              
              <h2 className="text-2xl font-semibold mt-8 mb-4">2. Definitions and key terms</h2>
              <p className="mb-4">
                To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:
              </p>
              <ul className="list-disc pl-6 mb-4">
                <li className="mb-2">Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
                <li className="mb-2">Company: when this policy mentions "Company," "we," "us," or "our," it refers to StartupFundr, that is responsible for your information under this Privacy Policy.</li>
                <li className="mb-2">Country: where StartupFundr or the owners/founders of StartupFundr are based, in this case is United States</li>
                <li className="mb-2">Customer: refers to the company, organization or person that signs up to use the StartupFundr Service to manage the relationships with your consumers or service users.</li>
                <li className="mb-2">Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit StartupFundr and use the services.</li>
                <li className="mb-2">IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.</li>
                <li className="mb-2">Personnel: refers to those individuals who are employed by StartupFundr or are under contract to perform a service on behalf of one of the parties.</li>
                <li className="mb-2">Personal Data: any information that directly, indirectly, or in connection with other information — including a personal identification number — allows for the identification or identifiability of a natural person.</li>
                <li className="mb-2">Service: refers to the service provided by StartupFundr as described in the relative terms (if available) and on this platform.</li>
                <li className="mb-2">Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.</li>
                <li className="mb-2">Website: StartupFundr's site, which can be accessed via this URL: www.startupfundr.com</li>
                <li className="mb-2">You: a person or entity that is registered with StartupFundr to use the Services.</li>
              </ul>
              
              <h2 className="text-2xl font-semibold mt-8 mb-4">3. Information We Collect</h2>
              <p className="mb-4">
                We collect information from you when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey or fill out a form.
              </p>
              <ul className="list-disc pl-6 mb-4">
                <li className="mb-2">Name / Username</li>
                <li className="mb-2">Email Addresses</li>
                <li className="mb-2">Password</li>
                <li className="mb-2">Phone Numbers</li>
                <li className="mb-2">Business Information</li>
                <li className="mb-2">Payment Information</li>
              </ul>
              
              <h2 className="text-2xl font-semibold mt-8 mb-4">4. How We Use Your Information</h2>
              <p className="mb-4">
                We use the information we collect in various ways, including to:
              </p>
              <ul className="list-disc pl-6 mb-4">
                <li className="mb-2">Provide, operate, and maintain our website</li>
                <li className="mb-2">Improve, personalize, and expand our website</li>
                <li className="mb-2">Understand and analyze how you use our website</li>
                <li className="mb-2">Develop new products, services, features, and functionality</li>
                <li className="mb-2">Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes</li>
                <li className="mb-2">Send you emails</li>
                <li className="mb-2">Find and prevent fraud</li>
              </ul>
              
              <h2 className="text-2xl font-semibold mt-8 mb-4">5. Security of Your Personal Information</h2>
              <p className="mb-4">
                We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.
              </p>
              
              <h2 className="text-2xl font-semibold mt-8 mb-4">6. Contact Us</h2>
              <p className="mb-4">
                If you have any questions about this Privacy Policy, please contact us at:
              </p>
              <p className="mb-4">
                StartupFundr<br />
                1234 Innovation Way<br />
                San Francisco, CA 94103<br />
                privacy@startupfundr.com<br />
                (555) 123-4567
              </p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
